### ISSUE TITLE
Error installing webmacs

### ISSUE THREAD

**Issue by domingoUnican** [parkouss/webmacs#1]
I am using ubuntu 16.04 and I tried to install it using:
pip install -e .

(inside the webmacs directory) and I got this message.

In file included from /home/domingo/Bin/webmacs/vendor/hashset-cpp/HashSet.cpp:6:0:
/home/domingo/Bin/webmacs/vendor/hashset-cpp/HashSet.h: In member function ‘void HashSet<T>::clear()’:
/home/domingo/Bin/webmacs/vendor/hashset-cpp/HashSet.h:234:5: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
     auto oldBucketCount = bucketCount;
     ^
/home/domingo/Bin/webmacs/vendor/hashset-cpp/HashSet.h:234:10: error: ‘oldBucketCount’ does not name a type
     auto oldBucketCount = bucketCount;
          ^
/home/domingo/Bin/webmacs/vendor/hashset-cpp/HashSet.h:236:10: error: ‘oldBucketCount’ was not declared in this scope
     init(oldBucketCount);

**Comment by parkouss** [comment]
hmm, I don't currently maintain the code of hashet (nor anything in the vendor directory which actually is useful for building the backend of ad blocking). My best guess is that your compiler does not understand well auto and the c++ 11 features.

Could you try changing the line:

`extra_compile_args=["-g0"],`
to
`extra_compile_args=["-g0", "-std=c++11"]`

In the setup.py file and tell me if that works?

**Comment by domingoUnican** [comment]
exactly!

I can't believe that you were so fast. Thank you very much. One question, is it possible to make a small donation to the project?

**Comment by parkouss** [comment]
ok, good to know that it worked for you :) I will fix that in the master branch as I believe this flag won't hurt anyone.

Hm, I have nothing set up so far to receive donations for the project, I might set up something and I will tell you at that time. Thanks for asking!
