### ISSUE TITLE
Feature request: Show url in mode line when selecting link to jump to

### ISSUE THREAD

**Issue by TLATER** [parkouss/webmacs#109]
It would be nice if the mode-line displayed the link I am about to jump to/copy/whatever (typically using `f`). This is handy on things like blogposts, where the actual location links point to is obscured.

Currently, the prompt will show something along the lines of `follow: #x`, where x is the number of the link that is being followed. I would like to see something like `follow: #x (https://github.com/parkouss/webmacs)`.

**Comment by parkouss** [comment]
This is already the case: by pressing f for example, the text input is opened at the bottom and on its right side the url is displayed when available.
