### ISSUE TITLE
Scrollbar width

### ISSUE THREAD

**Issue by deb75** [parkouss/webmacs#116]
Hello,

How do you customize the scrollbar width ?

If I am not mistaken, the doc does not talk about it.

I also use qutebrowser (qtwebengine), I manage to customize the scrollbar through a "user.css" and the option `c.content.user_stylesheets = ["user.css"]`

Does webmacs also work like this ?

Regards

**Comment by parkouss** [comment]
Hi,

Currently there is no way to customize the scrollbar. From what I understand qutebrowser is doing that by allowing to customize css on web pages - which webmacs does not support yet. So I believe that support for css is what we should focus on here - how does the code look like in your user.css file? just for my information :)

**Comment by deb75** [comment]
Hi,

Thanks for your fast answeer.

I was able to achieve it anyway by playing with  `QT_AUTO_SCREEN_SCALE_FACTOR` and `QT_SCALE_FACTOR` environment variables (because of my HiDPI screen).

The `user.css` for `qutebrowser` is the following :
```
::-webkit-scrollbar {
  width: 16px;
  height: 8px;
}

::-webkit-scrollbar-track:vertical {
  background: grey;
  border-left: 1px solid black;
}

::-webkit-scrollbar-thumb:vertical {
  background: white;
  border-left: 1px solid black;
}

::-webkit-scrollbar-track:horizontal {
  background: grey;
  border-radius: 4px;
}

::-webkit-scrollbar-thumb:horizontal {
  background: white;
  border-radius: 4px;
  box-shadow: inset 0 0 8px black;
}

::-webkit-scrollbar-corner {
  background: silver;
}
```

Hopes this help you in the future.

Regards
