### ISSUE TITLE
documentation typing error ?

### ISSUE THREAD

**Issue by GeorgSimon** [parkouss/webmacs#124]
Using the line
variables.set("webjump-default", "google ")
from [webmacs.readthedocs.io/en/latest/user_configuration.html](url)
I got an error:
webmacs.variables.VariableConditionError: Must be one of ('google', 'file', 'webmacs', 'http', 'https', 'duckduckgo')

variables.set("webjump-default", "google")
( without the space ) works fine.

( Now I use variables.set("webjump-default", "duckduckgo") )

**Comment by parkouss** [comment]
Totally right. Will fix it, thanks.
