### ISSUE TITLE
Nix package

### ISSUE THREAD

**Issue by jacg** [parkouss/webmacs#126]
I would like to make a [nix](https://nixos.org/nix/) package for webmacs. Before doing so, I would like to check

+ whether there is someone more qualified around here to make such a package: I am a nix novice;

+ whether a 0.8 release is planned any time soon: some useful features have been added since 0.7, and it would be satisfying if the nix package could be pinned to a release rather than a random commit.

**Comment by parkouss** [comment]
Hey @jacg ,
I just released a new 0.8 release, https://github.com/parkouss/webmacs/releases/tag/0.8. For the nix package, I can't help you :).

**Comment by jacg** [comment]
Great! I'll get on with the nix package myself, when I get some spare time. I'll close this once the package is ready.

**Comment by jacg** [comment]
The package has now been [merged](NixOS/nixpkgs#69088) into nixpkgs.

Conequently, webmacs can now be installed on Linux, macOS and other Unix-like system via the [nix](https://nixos.org/nix/) package manager.
