### ISSUE TITLE
Support reading auth data from external utility like pass

### ISSUE THREAD

**Issue by chaoflow** [parkouss/webmacs#140]
It would be great to have way to read auth data from https://www.passwordstore.org/ and other external utilities.

**Comment by TLATER** [comment]
While this is neat, I think it'd be better to have as a quasi add-on. It'd be pretty severe scope creep to try and support every password manager out there.

Maybe a bit of generic configuration support to pull passwords for a specific domain name from a command makes more sense?

**Comment by chaoflow** [comment]
Sure, good point. I rephrased the title accordingly.

**Comment by parkouss** [comment]
Don't know if that can be of any interest now, but I just looked again at webmacs and *huh surprise* it is working quite well for me (after a few python fixes...) So I just fixed the nits, and then as I too use pass as my main password manager (and passff) go ahead to make something working, at least for me. You can give it a test by adding:

`variables.set("password-manager", "passwordstore")`

in the __init__.py file, and then press `P` or manually execute the command `password-manager-fill-buffer` on a page for which passwords are configured. See https://github.com/passff/passff, file scheme is similar.

I'm closing the issue, don't hesitate to make a new one / comment if you'd like to.
