### ISSUE TITLE
Bookmark manager feature

### ISSUE THREAD

**Issue by jagguli** [parkouss/webmacs#18]
probably can modify the history implementation to make some sort of bookmark manager,

**Comment by parkouss** [comment]
I just pushed a set of commits for that :)

So basically:

- press M to create a new bookmark (bookmark-add)
- press m to open the bookmark's list, allowing to open a bookmark (bookmark-open)
- C-u m allow to open in a new buffer
- you can delete a bookmark by using C-k when there is a selection on the bookmark's list (same binding as for the buffer's list)
- bookmarks are completed and can be opened quickly using the go-to commands also (g binding)

That's it! Tell me if that fit your needs, and feel free to close the issue if that is the case.

**Comment by jagguli** [comment]
Looks good I'll test it out at work tomorrow. Where are the bookmarks stored? is it a redable format ?

**Comment by parkouss** [comment]
Sorry I missed your question - no currently this is sqlite-based, in its own database file: ~/.webmacs/profiles/default/bookmarks.db
