### ISSUE TITLE
Refine the zooming function

### ISSUE THREAD

**Issue by FoilKiter** [parkouss/webmacs#22]
Hi there
As it's my first post, let me first of all thank you Julien for the amazing work you've done. Really really great !
So my enhancement idea now : in Conkeror there was a distinctive feature, very useful : one could chose to either zoom in over the whole page, or just the text in it, so as not to lose the main page view.
For reference, it is explained at the bottom of [http://conkeror.org/QuickStart](url)
Not being a developer, I have no idea if that entails much work or not, but it could definitely be a useful improvement for those that spend too much time staring at a computer screen through the day- and night ;)

Arnaud

**Comment by parkouss** [comment]
Hi, thanks for the comment! I appreciate it. :) And I find the proposal really interesting too.

So I started to look at the code in conkeror, and it appears that it was using a firefox specific api to do that; though it may be possible to implement something similar, as there is some chrome extension that does that kind of stuff, like https://github.com/lihanli/chrome-text-only-zoom.

It would require to implement that kind of code in the javascript side of the browser, and call that from the python side. It is not that trivial, but certainly doable, I will look into it when I will find the time.

Thanks!

**Comment by FoilKiter** [comment]
Hello Julien, 
Well that is great news ! Don't put yourself under pressure, it could be a quite nice new feature (as shown by many comments from the Chrome extension you mentioned), but as it is, Webmacs is already quite functional, my daily driver to be honest, so take your time. "Pas le feu au lac" as we say around here ;)
Cheers

**Comment by parkouss** [comment]
Hey Arnaud, I just implemented the zoom text only using the code of the extension above (see f737e40b4a9632c45877a081481caa22a2375dea). It seems to works quite well, default bindings are under C-+, C-- and C-=. I hope you'll enjoy it, feel free to reopen the issue if there is any issue with that!
