### ISSUE TITLE
Protocols not giving initial completions

### ISSUE THREAD

**Issue by plafrance** [parkouss/webmacs#23]
Upon starting a url with a protocol (file://, http://, webmacs://, etc.) an search for completions should be started right away.

So, entering "webacs://" should give the possible completions "version, downloads". For now, one needs to enter an initial letter ("v" or "d") to fire up the search.

**Comment by parkouss** [comment]
I just fixed that, with some other fixes and improvements for the webjump completion. So it should be all good now with the latest code in the master branch.

Please reopen the issue if that's not working for you.
