### ISSUE TITLE
Prefix key stops working

### ISSUE THREAD

**Issue by plafrance** [parkouss/webmacs#26]
Sometimes afetr a while of usage, the prefix key (C-x) stops working as such. For instance, pressing C-x b does not run the command switch-buffer but rather buffer-history as when pressing only the b key. The same applies for any key binding combined with C-x.

The only way to restablish the prefix key seems to be restarting the browser.

It happends quite often but for the moment I am unable to describe a way of reproducing the problem.

**Comment by parkouss** [comment]
Recently I have changed the way keybindings are handled, maybe that helped. Could you tell me if you are able to reproduce it with current master?

**Comment by plafrance** [comment]
Hi Julien,
I've been using the current master (3e81ca0) for a few days now without the problem reappearing. The only change I had to make to stop the download_manager from crashing was this one : 

    --- a/webmacs/download_manager/__init__.py
    +++ b/webmacs/download_manager/__init__.py
    @@ -56,7 +56,7 @@ class DlPrompt(Prompt):
         download_started = Signal(object)
     
         def __init__(self, dl):
    -        Prompt.__init__(self)
    +        Prompt.__init__(self, None)
             self._dl = dl
             self.label = "Download file [{}]:".format(dl.mimeType())

I'm not sure passing None is the correct thing to do, so I'm not going to commit my change.

Thanks for the bugfix, it does help a lot.

Patrick

**Comment by plafrance** [comment]
Ho, you did correct that, never mind. I'm going to keep testing with the most recent master.

**Comment by parkouss** [comment]
Hey, thanks Patrick!

Yeah I was doing some refactoring in the code, and I forgot to test that. Thanks for telling me anyway :)

**Comment by plafrance** [comment]
The original problem seems to have been fixed. Closing the issue.
