### ISSUE TITLE
Highlight confirmation prompt.

### ISSUE THREAD

**Issue by jagguli** [parkouss/webmacs#34]
often times I'm filling forms etc .. and try to leave the page .. I get stuck, only to realize there is a prompt blocking the page exit.

The prompt needs to be highlighted that it grabs my attention requiring an action.

Also there is a (prbably a seperate) issue, that it is possible to loose focus of the confirmation prompt, then having to reacth for the mouse to gain focus again.

**Comment by parkouss** [comment]
Excellent idea to highlight or flash the prompt!

**Comment by parkouss** [comment]
I just added some code for that, please tell me if that suits your needs.
