### ISSUE TITLE
Make confirmation prompt modal

### ISSUE THREAD

**Issue by jagguli** [parkouss/webmacs#35]
It is possible to loose focus of the confirmation prompt, then having to reacth for the mouse to gain focus again.

**Comment by parkouss** [comment]
Yeah, I would prefer not to make the confirmation prompt modal (this is a personal preference!) but I could eventually add a variable to allow to make them modal.

The focus should not be lost on confirmation prompt, so that is a bug :) Do you know how to reproduce it to help me fix that?

**Comment by parkouss** [comment]
I may have fixed the problem, as I found a related bug and fixed it. Though maybe it is not exactly the same, so I'll wait for your input if you can reproduce it before closing this issue.

**Comment by jagguli** [comment]
Haven't had this issue lately, so closing. Thanks
