### ISSUE TITLE
webmacs does not start under Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [parkouss/webmacs#36]
I build webmacs from git.

Running webmacs only gives 

'NoneType' object has no attribute 'windowFlags'

**Comment by parkouss** [comment]
Ok that's strange, because I often runs it from arch linux myself. Could you paste me the whole stack trace please?

**Comment by stefanhusmann** [comment]
Never Mind, I cannot reproduce it now, after deleting my ~/.webmacs directory it works again. Sorry for the noise.
