### ISSUE TITLE
Emacs org-protocol capture

### ISSUE THREAD

**Issue by inglada** [parkouss/webmacs#45]
Hi,
I am a conkeror user and I would like to move to webmacs. I use a lot [emacs org-mode and its org-protocol](http://orgmode.org/worg/org-contrib/org-protocol.html) to store links and page contents from conkeror. My .conkerorrc has this for that:
```
function org_capture (url, title, selection, window) {
    var cmd_str = 'emacsclient \"org-protocol://capture://'+url+'/'+title+'/'+selection+'\"';
    if (window != null) {
      window.minibuffer.message('Issuing ' + cmd_str);
    }
    shell_command_blind(cmd_str);
}

interactive("org-capture", "Clip url, title, and selection to capture via org-protocol",
          function (I) {
              org_capture(encodeURIComponent(I.buffer.display_uri_string), encodeURIComponent(I.buffer.document.title), encodeURIComponent(I.buffer.top_frame.getSelection()), I.window);
          });

function org_store_link (url, title, window) {
    var cmd_str = 'emacsclient \"org-protocol://store-link://'+url+'/'+title+'\"';
    if (window != null) {
      window.minibuffer.message('Issuing ' + cmd_str);
    }
    shell_command_blind(cmd_str);
}

interactive("org-store-link", "Stores [[url][title]] as org link and copies url to emacs kill ring",
          function (I) {
              org_store_link(encodeURIComponent(I.buffer.display_uri_string), encodeURIComponent(I.buffer.document.title), I.window);
          });

define_key(content_buffer_normal_keymap, "C-c r", "org-capture");
define_key(content_buffer_normal_keymap, "C-c l", "org-store-link");
```

I have started to port this into the __init__.py. I have created the keymaps and coded the python function to call org-protocol, but I am lacking the commands to retrieve the URL of the current buffer or get any text selection from the page. 

Where can I find the functions which to that?

I would also like to write some messages on the minibuffer.

Thanks.

**Comment by parkouss** [comment]
Hi @inglada,

Thanks for looking into webmacs. What you want to do is totally doable, though there is no documentation to help you do that yet;

So, one thing that can help is to look at the source code of a core function of webmacs. For example, go-forward is usually bound to F, so you can do the following:

- C-h k F (to open the documentation about the binding)
- follow the go-forward link in there
- now follow the source code link so you can see how the action is implemented.

You will find that a webmacs command is implemented using a define_command decorator:

```python
from webmacs.commands import define_command

@define_command("org-store-link")
def org_store_link(ctx):
    pass
```

The ctx parameter is an instance of webmacs.CommandContext, defined in the toplevel \_\_init\_\_.py file. It contains two members that are going to be useful for you:

- buffer (an instance of QWebEnginePage, see http://doc.qt.io/qt-5/qwebenginepage.html)
- minbuffer (an instance of webmacs.minibuffer.Minibuffer)

So you can do:

```python
# returns a string of the current selection
ctx.buffer.selectedText()

# returns the page title
ctx.buffer.title()

# returns the buffer url, as a string
ctx.buffer.url().toString()

# and to print a message on the minibuffer
ctx.minibuffer.show_info("display me")
```

Then you need to map your command to some binding.

```python
from webmacs import keymaps

buffer_keymap = keymaps.webbuffer_keymap()
buffer_keymap.define_key("C-c l", "org-store-link")
```

Hope that helps. By the way, once you have it working it would be good to have this as an example for others, or maybe to have this directly in webmacs (maybe as a "plugin", not activated by default but simple to set up). Please tell me when you are done here (or if you need some more help from me), and then we could discuss about how to share some knowledge here if you agree.

**Comment by inglada** [comment]
Hi,

Thanks for your help. The following works for me:

```
import os
from webmacs.commands import define_command

@define_command("org-capture")
def org_capture(ctx):
    url = ctx.buffer.url().toString()
    title = ctx.buffer.title()
    selection = ctx.buffer.selectedText()
    cmd_str = 'emacsclient \"org-protocol://capture?&url='+url+'&title='+title+'&body='+selection+'\"'
    ctx.minibuffer.show_info(cmd_str)
    os.system(cmd_str);

from webmacs import keymaps

buffer_keymap = keymaps.webbuffer_keymap()
buffer_keymap.define_key("C-c r", "org-capture")

```

The `org-store-link` would be very similar. 

I will close this issue, as you suggest. I guess there are many other things that we could do with org-mode or more generally emacsclient.

Cheers.
