### ISSUE TITLE
package releases?

### ISSUE THREAD

**Issue by bremner** [parkouss/webmacs#49]
The github generated tarballs are not very useful because they are missing the submodules.

**Comment by parkouss** [comment]
Indeed, that's a good point. Github is generating them automatically for each tag, but I guess using travis we could at least push full source tarballs.

**Comment by parkouss** [comment]
Started from the next release, there will be a file in the releases section of github that will hold a webmacs-$version.tar.gz source file, containing all the necessary files to build webmacs (though not the python dependencies).
