### ISSUE TITLE
imports in docs

### ISSUE THREAD

**Issue by bremner** [parkouss/webmacs#52]
I'm using python 3.6.6

1. This is purely a python issue, I guess: `import .webjumps` didn't work for me [1]
but `from . import webmacs` does

2. This is possibly obvious to some, but webjumps.py (or wherever the webjumps are defined) needs
something like  `from webmacs.commands.webjump import define_webjump` at the top

[1]: https://webmacs.readthedocs.io/en/latest/user_configuration.html#using-more-than-one-configuration-file

**Comment by bremner** [comment]
I should say I don't mind working up a pull request, if what I've suggested looks correct.

**Comment by parkouss** [comment]
Sure, please go ahead! I guess you meant `from . import webjumps` though.
