### ISSUE TITLE
resizing columns

### ISSUE THREAD

**Issue by bremner** [parkouss/webmacs#53]
One of the sites I visit (mastodon) has very narrow columns, which is annoying for me. On conkeror / firefox when I resize the text, the column grows with it. When I resize the text in webmacs the column size is fixed. I'm not sure if that's intentional, but I guess I would like either

- the columns to grow when the text in them resizes
- some way to override the CSS for a particular site.

Any suggestions?

Thanks,

David

**Comment by parkouss** [comment]
There are currently two way to zoom in webmacs:

- normal zoom (using +, -, =)
- text zoom (C-+, C--, C-=)

Which one did you try? I think the normal zoom should do what you want.

For the css proposal, I am sure we can do that. We can think about it in a separate issue maybe.

**Comment by bremner** [comment]
Oh, that's correct, +/- is exactly what I wanted. I guess I just need to stare harder at the list of keybindings in the future. As far as overriding css, I'm not sure about what the issues really are, maybe I'll let someone more knowledge open an issue (at least I'll wait a bit).

**Comment by bremner** [comment]
By the way, I think I figured out the source of confusion (well, an excuse anyway ;).
The roles of + and C-+ seem to be interchanged in conkeror and webmacs. Not sure if that is intentional, or if it's too late to change the defaults.

**Comment by parkouss** [comment]
Hmm, I would rather keep the default bindings as they are now, though you can rebind them as in conkeror with a few configuration lines.
