### ISSUE TITLE
Ability to copy the focused URL with one key/yank

### ISSUE THREAD

**Issue by tinder-jonathanwilner** [parkouss/webmacs#56]
I can't figure out how to yank the current URL for inserting somewhere else. When I try "C", I get the first URL generated by the link numbering. 

This is the "yy" binding in Vimium, Qutebrowser, etc. It's super useful for sending a link to somewhere else.

**Comment by parkouss** [comment]
There is no way to copy the current url right now. There is only "c", then hitting some text/number to select which link to copy.

1. It would be interesting to have something like what you suggest. Something that I can think of, and that is quite simple to implement, is to change a bit the keybindings:

- "c l" to copy a link (currently bound to "c")
- "c L" to copy the current link

And then others copies commands could be:

- "c u" for current page url (currently quite magic "c 0")
- "c i" for image
- "c I" for current image

2. Another possibility would be to make the hinting automatically default to the active element if there is any, but this is more work.

3. Find a totally new binding for copying current url. (BTW not that hard, I could help you to add such a command and binds it in your local config only)

I think i am in favor of 1. This is a change from the conkeror bindings and for the current bindings, but that make more sense to me. Any thought?

**Comment by tinder-jonathanwilner** [comment]
I think option 1 works well enough - similar to the Qutebrowser use of Vim's y. I do like using something like "cc" so that you hit the same key twice to get the URL.  It's fast for the repetitive action.

I'd also like to see it auto-copied without hitting enter - the second key should initiate the action.

**Comment by parkouss** [comment]
Hey @tinder-jonathanwilner , I created the PR #61 which should fix the issue.

It define new bindings for copying stuff to clipboard:

- "c l" copy-link (bound to "c" in master branch)
- "c c" copy-current-link (what you are asking for)
- "c t" copy-current-buffer-title
- "c u" copy-current-buffer-url

If you have some time, please give it a try and tell me if that suit your needs :)

**Comment by parkouss** [comment]
I just merged the above PR. Seems like *c c* was not working for you, let's continue the discussion here about that.

**Comment by tinder-jonathanwilner** [comment]
hi @parkouss  - I should have given you faster feedback. The above PR actually did work perfectly - you and I had a misunderstanding. The action I was desired was the c u binding - not the c c binding (which is actually very cool - giving a lot more choices to copy!).

However, it looks like in the merged PR, c u and c l are doing the same thing. When I hit c u, i get the "copy link" prompt in the mini buffer, not the copying of the URL I was on.

**Comment by parkouss** [comment]
closing the issue as I have the feeling it's good enough now. Please reopen if I'm wrong.
