### ISSUE TITLE
Change link hints to letters vs. numbers

### ISSUE THREAD

**Issue by tinder-jonathanwilner** [parkouss/webmacs#57]
Hi there - again like vimium or qutebrowser, I'd love the option to have link hinting by letters. This means less finger movement up to the number row for me.

**Comment by parkouss** [comment]
Yeah, I thought about it a couple of times too :)

Well it is quite some work, but definitely something that I would like in webmacs, as an alternative to the current "way of hinting".

**Comment by tinder-jonathanwilner** [comment]
Cool! And related to my other post re: copying URLs, it would be great if when the user types the hint completely, the browser opens the URL - currently we have to hit enter via the status bar at the bottom of the browser.

**Comment by parkouss** [comment]
I created the branch alphabet-hint  and there is a working version that you can try out.

You can checkout it, then in the configuration file:

`from webmacs import variables`
`variables.set("hint-method", "alphabet")`
And optionally,
`variables.set("hint-alphabet-characters", "auie,ctsrn")`

It is also possible to customize the style with the hint-node-style variable (you can run M-x describe-variable on it for some help)

Also I changed the style of the hints, tell me what do you think of it.

**Comment by tinder-jonathanwilner** [comment]
Hi @parkouss - this is working perfectly - exactly as I expected, with the automated execution - no need to hit Enter. I love the new hinting style as well. Thank you!

**Comment by parkouss** [comment]
Awesome :) I just merged it (#64).
