### ISSUE TITLE
python -m webmacs.main failed

### ISSUE THREAD

**Issue by FirstLoveLife** [parkouss/webmacs#58]
```
(venv) ~/dev/webmacs >>> python -m webmacs.main                                                                                                                                           ±[●][master]
/home/firstlove/dev/webmacs/webmacs/main.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/firstlove/dev/webmacs/venv/lib/python3.7/site-packages/dateparser/date.py:319: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(languages, (list, tuple, collections.Set)) and languages is not None:
/home/firstlove/dev/webmacs/venv/lib/python3.7/site-packages/jinja2/utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/home/firstlove/dev/webmacs/venv/lib/python3.7/site-packages/markupsafe/__init__.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
/home/firstlove/dev/webmacs/webmacs/commands/webjump.py:373: DeprecationWarning: invalid escape sequence \S
  if re.match("^\S+://.*", value):
[0829/170115.084362:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/firstlove/#8697174 (deleted)
  Error: No such file or directory
/home/firstlove/dev/webmacs/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:3245: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  elif isinstance( exprs, collections.Iterable ):
```

I have followed previous steps in readme. But error occur

Quit venv then try again:
```
~/dev/webmacs >>> python -m webmacs.main                                                                                                                                                  ±[●][master]
/home/firstlove/dev/webmacs/webmacs/main.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/firstlove/dev/webmacs/webmacs/main.py", line 263, in <module>
    main()
  File "/home/firstlove/dev/webmacs/webmacs/main.py", line 216, in main
    from .application import Application, _app_requires
  File "/home/firstlove/dev/webmacs/webmacs/application.py", line 29, in <module>
    from .adblock import Adblocker, AdblockUpdateRunner, adblock_urls_rules
  File "/home/firstlove/dev/webmacs/webmacs/adblock.py", line 22, in <module>
    import dateparser
ModuleNotFoundError: No module named 'dateparser'
```
```
~/dev/webmacs >>> python --version                                                                                                                                                        ±[●][master]
Python 3.7.0                                                                                                                                                                     ±[●][master]
~/dev/webmacs >>> uname -a                                                                                                                                                                ±[●][master]
Linux manjaro 4.18.4-1-MANJARO #1 SMP PREEMPT Wed Aug 22 22:33:53 UTC 2018 x86_64 GNU/Linux
```

**Comment by parkouss** [comment]
First, thanks for reporting this. :)

Hmm, I never tried yet with a python 3.7 version, and looking at your first trace there are a couple of deprecation warnings that needs to be addressed. However from this message I do not see any error, only warnings (there is no traceback). The Error: failed to open file line is something that shows up normally, it is a chromium issue but does not prevent webmacs from running well.

So what is hapenning exactly? Do you see a window? Is the shell blocking and never returning?

Outside of the virtualenv, the issue you are seeing is that the system is missing a dependency. I think installing within virtualenv is the way to go, so I suggest that you don't try this. If you really want to, you can search with your package manager for the dependencies (or use pip install with sudo) and install the python-dateparser dependency you can see in the traceback (and a few other probaly).

I will try to install a python 3.7, and install webmacs in there to try that. In the mean time, I would appreciate more details of what you see while trying in the virtualenv.

**Comment by FirstLoveLife** [comment]
I cannot see any window/buffer popup at the first time I open it(`python -m webmacs.main`), however, I open it again, the windows occur and works fine : )
![image](https://user-images.githubusercontent.com/37442588/44784043-d1fdb080-abbe-11e8-9ede-bf46dd9d7abc.png)

But I am in china, so I cannot connect google.com unless use socks5/shadowsocks(or other alternatives), is it possible to use proxy for webmacs, I really love the feeling!

**Comment by FirstLoveLife** [comment]
kk

**Comment by parkouss** [comment]
Ok, that's cool if that works now; I am not sure what was the issue though (for not showing the window), if that happen again, please open a specific issue.

For the proxy, it requires some development I think. I will open an issue for that and work on it as soon as I can (probably in a couple of days). I will ask you to try out once it's ready.

**Comment by FirstLoveLife** [comment]
Thanks for your awesome contributions!

**Comment by parkouss** [comment]
Thanks! I just opened the issue #59 for proxy support. Closing this issue, feel free to reopen a more specific for the window not showing if you see that again.
