### ISSUE TITLE
all visited pages are blank

### ISSUE THREAD

**Issue by bremner** [parkouss/webmacs#6]
I can enter a URL using C-x C-f, and the title bar changes, but it seems no matter what I enter the resulting page is blank. I followed the virtualenv install on Debian testing (python 3.6).  There is no debugging output on the console (C-x C-c also works to quit)

**Comment by parkouss** [comment]
Currently you have to type a complete url in there, or a webjump.

<C-x C-f> or <C-u g> and:
https://github.com/parkouss/webmacs/issues/6

Should work. It works for me. If not, can you try with enabling the logs (-l debug -w info) and see if something is interesting in there?

Also webjumps should work - so instead of using a full url, you can for example execute a google search with <C-x C-f> and:
google my query

**Comment by parkouss** [comment]
Sorry, I think I missed the information that the title bar changes - so I believe the page is loaded, but for some reason it is not well displayed. Were you able to see a page before, or is it like that with a fresh install?

What is the version of Qt/PyQt? I could try later to install a debian and see if I'm having the same issue.

**Comment by bremner** [comment]
Julien Pagès <notifications@github.com> writes:

> Sorry, I think I missed the information that the title bar changes - so I believe the page is loaded, but for some reason it is not well displayed. Were you able to see a page before, or is it like that with a fresh install?
>

This is with a fresh install.

> What is the version of Qt/PyQt? I could try later to install a debian and see if I'm having the same issue.

I am using pyqt 5.9.2+dfsg-1

The qt libs seem to have similar versions:

e.g. libqt5webengine5 is 5.9.2+dfsg-1

d

**Comment by parkouss** [comment]
So to be sure, do you see in the title page the title of the page if it has been loaded?

E.g with `https://github.com/parkouss/webmacs/issues/6`you see something like `all visited pages are blank . issue #6 . parkouss/webmacs - Webmacs`, right?

**Comment by bremner** [comment]
Julien Pagès <notifications@github.com> writes:

> So to be sure, do you see in the title page the title of the page if it has been loaded?
>
> E.g with `https://github.com/parkouss/webmacs/issues/6`you see
> something like `all visited pages are blank . issue #6
> . parkouss/webmacs - Webmacs`, right?
>

Just

"github.com - Webmacs" for that url

Here's the debug output

INFO: loading adblock cached data: /home/bremner/.webmacs/adblock/cache.dat
DEBUG: local keymap activated: webbuffer
INFO: filtered: https://github.com/parkouss/webmacs/issues/6
ERROR webcontent: [https://github.com/parkouss/webmacs/issues/6] Uncaught ReferenceError: jstProcess is not defined
INFO: checking autofill for github.com
INFO webcontent: [https://github.com/parkouss/webmacs/issues/6] registering...
DEBUG: local keymap activated: webbuffer

**Comment by parkouss** [comment]
Looks like it is a debian issue: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1565847.html

With some luck, you might be able to install PyQt5 in you virtualenv using pip (do not forget to activate it),

`pip install PyQt5`

If that does not work, the last thing I can think of is manually building Qt and PyQt.

**Comment by The-Compiler** [comment]
Note that that issue is only about error pages being broken, not page loading in general.

**Comment by parkouss** [comment]
Oh thanks @The-Compiler, I am wrong then and it must be something else.

**Comment by parkouss** [comment]
Still @bremner it would be a good start to see if the minimal test script works for you (only test with the --webengine flag as it is the only backend supported here):

https://github.com/qutebrowser/qutebrowser/blob/master/scripts/testbrowser.py

**Comment by The-Compiler** [comment]
Oh - I recently refactored the testbrowser code to be two separate (but more minimal) scripts, but apparently didn't delete the old one.

Here's the new, QtWebEngine-only one: https://github.com/qutebrowser/qutebrowser/blob/master/scripts/testbrowser/testbrowser_webengine.py

**Comment by bremner** [comment]
Florian Bruhin <notifications@github.com> writes:

> Oh - I recently refactored the testbrowser code to be two separate (but more minimal) scripts, but apparently didn't delete the old one.
>
> Here's the new, QtWebEngine-only one: https://github.com/qutebrowser/qutebrowser/blob/master/scripts/testbrowser/testbrowser_webengine.py
>

╭─ zancas:~ 
╰─% python3 testbrowser_webengine.py url=https://www.google.com   
Loading progress: 10%
zsh: segmentation fault  python3 testbrowser_webengine.py url=https://www.google.com
[699:699:0100/000000.540673:ERROR:broker_posix.cc(41)] Invalid node channel message

**Comment by parkouss** [comment]
So it looks like you have a problem with the PyQt/Qt installation on your system. Have you tried to install PyQt5 through pip, or is it the version provided by debian? In any case, you can try the alternative and see if that works.

**Comment by bremner** [comment]
Julien Pagès <notifications@github.com> writes:

> So it looks like you have a problem with the PyQt/Qt installation on
> your system. Have you tried to install PyQt5 through pip, or is it the
> version provided by debian? In any case, you can try the alternative
> and see if that works.

This is the version on Debian. I guess I'll start by reporting a Debian
bug in pyqt5. I prefer to avoid pip.

**Comment by The-Compiler** [comment]
Note PyQt5 is only a (relatively thin) Python wrapper - you might want to report a bug against QtWebEngine instead. Maybe try reproducing it in a C++ QtWebEngine browser such as QupZilla, though.

You might also want to try qutebrowser (in the testing repos), it's PyQt and has various workarounds for Qt bugs (one or two which might be related) - if that works, maybe there's something webmacs can do.

**Comment by bremner** [comment]
Florian Bruhin <notifications@github.com> writes:

> Note PyQt5 is only a (relatively thin) Python wrapper - you might want
> to report a bug against QtWebEngine instead. Maybe try reproducing it
> in a C++ QtWebEngine browser such as QupZilla, though.

Hopefully the maintainers can sort that out.

> You might also want to try qutebrowser (in the testing repos), it's
> PyQt and has various workarounds for Qt bugs (one or two which might
> be related) - if that works, maybe there's something webmacs can do.

Yes, qutebrowser seems to run, visited a few URLs

d

**Comment by The-Compiler** [comment]
They're mostly [around here](https://github.com/qutebrowser/qutebrowser/blob/v1.0.4/qutebrowser/misc/backendproblem.py#L159-L242). Note that those things are rather tricky, as they need to happen in a specific sequence at a specific point in time on initialization.

**Comment by parkouss** [comment]
Awesome thank you.

I believe it is the first function highlighted above.  @bremner, do you mind giving a try by patching the webmacs/application.py file, adding those lines somewhere at the beginning of the file:

`import ctypes, ctypes.util`
`ctypes.CDLL(ctypes.util.find_library("GL"), mode=ctypes.RTLD_GLOBAL)`

Please let me know how if that helps.

**Comment by parkouss** [comment]
Ok, I just put that fix in webmacs anyway, as it seems a common issue on linux with nvidia cards. You can pull the latest sources and tell me if the issue is fixed.

**Comment by bremner** [comment]
Julien Pagès <notifications@github.com> writes:

> Ok, I just put that fix in webmacs anyway, as it seems a common issue on linux with nvidia cards. You can pull the latest sources and tell me if the issue is fixed.
>

Unfortunately not. It seems the same.

By the way, here's there debian bug I reported.

   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886400

d

**Comment by bremner** [comment]
I finally rebuilt from today's source 0.5-31-gaa598e1, and it seems OK. I am filing this reply using webmacs!
