### ISSUE TITLE
incompatible with qtwebengine < 5.8

### ISSUE THREAD

**Issue by bremner** [parkouss/webmacs#63]
It would be helpful to have minimum versions of the dependencies documented. Today I discovered (trying to get webmacs running on debian stable)

```text
 File "/usr/bin/webmacs", line 11, in <module>
    load_entry_point('webmacs==1.0', 'console_scripts', 'webmacs')()
  File "/usr/lib/python3/dist-packages/webmacs/main.py", line 238, in main
    else "webmacs-%s" % opts.instance
  File "/usr/lib/python3/dist-packages/webmacs/application.py", line 130, in __init__
    self.profile.enable(self)
  File "/usr/lib/python3/dist-packages/webmacs/profile.py", line 83, in enable
    self.update_spell_checking()
  File "/usr/lib/python3/dist-packages/webmacs/profile.py", line 46, in update_spell_checking
    self.q_profile.setSpellCheckEnabled(bool(dicts))
AttributeError: 'QWebEngineProfile' object has no attribute 'setSpellCheckEnabled'
```

A little poking at qt docs suggests that method was added in 5.8

**Comment by bremner** [comment]
We actually have qt 5.7.1 on debian stable. If webmacs can work with qt that old that would be great, but I understand it might just be too much work.

**Comment by parkouss** [comment]
So it was not much work to be able to support qt 5.8. Though there are some limitations (see the changes in the README), most importantly before 5.10 iframe support is not good and you might have issues related to that. Just open a specific issue if that happen, we'll see at that time.

**Comment by bremner** [comment]
Julien Pagès <notifications@github.com> writes:

> Also note you might try to install PyQt5 using pip in the virtualenv, it works on most systems I think (it is ok on arch, not sure about debian stable):
>
> `pip install PyQt5`
>

I can confirm master is running OK (at least for a few minutes!) on
debian stable, using system pyqt5

Thanks a lot, that's really helpful for me.

d
