### ISSUE TITLE
Feature request: C-x C-v, find-alternate-url command

### ISSUE THREAD

**Issue by xantoz** [parkouss/webmacs#69]
Like in conkeror, and find-alternate-file in emacs.

**Comment by parkouss** [comment]
Can you remind me what that comment does?

**Comment by xantoz** [comment]
It opens the url/webjump minibuffer but with the currently URL already inputted so that you can edit it. Use-case is the same as when you click the URL bar in a typical browser and proceed to edit the URL, not erasing it completely.

E.g. I'm currently on https://github.com/parkouss/webmacs/issues/69 and I might want to quickly go two steps up to https://github.com/parkouss/webmacs/ so I press C-x C-v M-backspace M-backspace RET

**Comment by parkouss** [comment]
ok, there is a binding for it but it is different, it is G. The command is called go-to-selected-url.

I don't mind binding it to C-x C-v too by default if want.

**Comment by xantoz** [comment]
Tried it just now. It would be nice if `go-to-selected-url` didn't automatically mark the entire URL (or at least for this functionality to be available as a variant), but instead just place the caret at the end. Because otherwise the URL will dissappear as soon as I start typing, a use-case which is already covered by regular **g**.

See my remark about the use-case for **g** being similar to double-clicking the address bar in a typical browser.

**Comment by parkouss** [comment]
I like your proposal, it sounds really great to me. To recap:

- consider some characters as being part of a word (similarly to what emacs does in fact) I can think about #/.-_: right now. Those will change the behavior of M-b, M-n, M-d and M-backspace.
- the *g* binding should by default show the current url selected, as the current G does. It should not break any usage as typing any letter will just clear that selection anyway.
- *G* binding will default with the current url not being selected, and the cursor at the end.

**Comment by xantoz** [comment]
First thanks. **G** works great now.

However, if I may be so rude, I have one additional request: I would like if there was a configuration option to make **g** and **C-x C-f** behave more closely to conkeror. That is, that they open with an empty minibuffer. 

While having the current URL there marked works fine when you start typing the URL, as the marked text will simply vanish, it interferes when you are pasting an URL from the primary buffer using mouse middle click, requiring me to first remove the text using backspace or similar. <sub>Pasting from the clipboard buffer using C-y or S-Insert (although S-Insert should really be pasting from primary) works ok.</sub>
