### ISSUE TITLE
Cannot launch from Master, tests failing

### ISSUE THREAD

**Issue by tinder-jonathanwilner** [parkouss/webmacs#77]
Hi - 

I updated to the latest master & can now not launch Webmacs. I get a brief pop-up / window flash, and then it closes with no errors listed to debug. 

I also ran the test suite - which does result in the GUI popping up during almost all the tests, then ending when it fails the final one. 

I've pasted the test results below:

`
(venv) jonwilner:webmacs jonwilner$ py.test ~/src/webmacs/tests --no-xvfb
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.7.0, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
PyQt5 5.11.2 -- Qt runtime 5.11.1 -- Qt compiled 5.11.1
rootdir: /Users/jonwilner/src/webmacs, inifile:
plugins: xvfb-1.1.0, qt-3.0.2, mock-1.10.0
collected 17 items                                                                                                                                                             

tests/test_prompt_history.py .                                                                                                                                           [  5%]
tests/test_variables.py .....                                                                                                                                            [ 35%]
tests/integration/test_copy_link.py ....                                                                                                                                 [ 58%]
tests/integration/test_iframe_navigation.py F..                                                                                                                          [ 76%]
tests/integration/test_javascript_prompt.py ...                                                                                                                          [ 94%]
tests/integration/test_navigation.py .                                                                                                                                   [100%]

=================================================================================== FAILURES ===================================================================================
____________________________________________________________________________ test_iframe_navigation ____________________________________________________________________________

session = <conftest.TestSession object at 0x115be07f0>

    def test_iframe_navigation(session):
        """
        Webcontent-edit keymaps are used even in sub frames.
        """
        session.load_page("iframe_follow", wait_iframes=True)
    
        session.wkeyclicks("Tab")
        session.check_javascript("%s === document.activeElement" % INPUT0, True)
    
        # type some text in INPUT0 and move word backward
    
        session.keyclicks("hello world")
        session.check_javascript("%s.value" % INPUT0, "hello world")
        session.check_javascript("%s.selectionEnd" % INPUT0, 11)
        session.wkeyclicks("M-b")
>       session.check_javascript("%s.selectionEnd" % INPUT0, 6)

tests/integration/test_iframe_navigation.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <conftest.TestSession object at 0x115be07f0>, script = "document.getElementById('input0').selectionEnd", return_value = 6
buffer = <webmacs.webbuffer.WebBuffer object at 0x10c604708>

    def check_javascript(self, script, return_value, buffer=None):
        buffer = buffer or self.buffer
        result = [None]
    
        if return_value is None:
            raise ValueError("return value can't be None")
    
        def ready():
            if result[0] == return_value:
                return True
            buffer.runJavaScript(script, lambda r: result.__setitem__(0, r))
    
>       assert self.wait_until(ready), "javascript result was %r" % result[0]
E       AssertionError: javascript result was 11
E       assert False
E        +  where False = <bound method TestSession.wait_until of <conftest.TestSession object at 0x115be07f0>>(<function TestSession.check_javascript.<locals>.ready at 0x10c60b950>)
E        +    where <bound method TestSession.wait_until of <conftest.TestSession object at 0x115be07f0>> = <conftest.TestSession object at 0x115be07f0>.wait_until

tests/integration/conftest.py:179: AssertionError
=============================================================================== warnings summary ===============================================================================
/Users/jonwilner/src/venv/lib/python3.7/site-packages/dateparser/date.py:319: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(languages, (list, tuple, collections.Set)) and languages is not None:

/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/markupsafe/__init__.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============================================================== 1 failed, 16 passed, 2 warnings in 6.50 seconds ================================================================`

**Comment by tinder-jonathanwilner** [comment]
Believe this was in error - It was launching properly but not visible! Doh!

**Comment by parkouss** [comment]
I think I already seen that: webmacs seems to be launched but there is no visible window. I wonder if this is a qt webengine bug (I believe it probably is) - but this would require some more investigation. I'll look at the above test failure when I'll have some time too, though it does pass on travis and locally for me.
