### ISSUE TITLE
Access to history when opening new buffer

### ISSUE THREAD

**Issue by inglada** [parkouss/webmacs#78]
Is there a way to use the history of visited buffers when creating a new buffer (C-x C-f)? Right now, what I do is C-x C-f to open an existing webjump (i.e. duckduckgo), then 'h' to access the history, but this is not very smart.

Thanks.

**Comment by parkouss** [comment]
Yes, <C-u h>. C-u is often used to open in new buffer. I am currently working on better documentation, I'll try to not forget about mentioning it. :)

**Comment by inglada** [comment]
That works. Thanks!

**Comment by parkouss** [comment]
Huh not sure what happened with my previous message - for the record, the key chord to use is:

`C-u h`
