### ISSUE TITLE
Choose file name when downloading a file

### ISSUE THREAD

**Issue by inglada** [parkouss/webmacs#79]
By default, downloaded files are written to $HOME/Downloads. Is there a way to choose the directory and or the file name?

Thanks

**Comment by inglada** [comment]
One interesting thing would be to propose as default dir the last one used, so that when editing the prompt, there is few things to edit.

**Comment by parkouss** [comment]
@inglada you mean a directory that would persist the time of the session, or that would live across restarts (so saved in a persistent way?)

I would be in favor of:
- having a variable to keep the last default used dir (what you are asking for) for the time webmacs is alive
- having another variable to override the default download dir.

Would that be ok for you?

**Comment by parkouss** [comment]
Should be fixed with #86 , there is now **default-download-dir** and **keep-temporary-download-dir** variables. (you can have the descriptions with the describe-variable command).

Please reopen if it does not work for you.
