### ISSUE TITLE
Is there a way to launch url in new buffer

### ISSUE THREAD

**Issue by jagguli** [parkouss/webmacs#8]
Hi I've  been using webmacs for a while and as a former conkeror user, I'm lovin it.

Is there way to open a url in new buffer.

like

`webmacs https://google.com`

should open in an existting session instead of opening a new window

**Comment by parkouss** [comment]
Oh, I thought that was the default, I guess I have broken that. I will try to look into it soon, should not be hard to fix I think.

**Comment by parkouss** [comment]
Ok, so I can confirm that this is currently the default (and only available) behavior on the master branch. From what I can see this is working as expected.

E.g if in a shell I do (without any running webmacs instance):

`python -m webmacs.main`

This run webmacs. Now in another shell I type:

`python -m webmacs.main https://google.com`

There is a new buffer opened for the given adress, not a new webmacs instance.

Note I am currently testing on a fedora, not sure how that can make a difference but just in case; And I suppose that your `webmacs` command is similar to the `python -m webmacs.main` command I used.

Could you explain me what you are doing exactly, maybe with some information of your OS so I can try to reproduce it?

THa

**Comment by jagguli** [comment]
hmm im just using the default webmacs command.

I installed from source and ran it as `webmacs http://google.com`

I tried `python -m webmacs.main https://google.com` same result

im on arch linux using python3

**Comment by parkouss** [comment]
Ok, the easyiest thing I can see to work on this is to add some debugging information using logs, then you could report what is logged. I might not be able to work on this soon (until few weeks) so feel free to look at it if you want and if you have the time. The code responsible of that is in the main.py file (look for IpcServer stuff) and in the ipc.py file.

**Comment by jagguli** [comment]
I don't understand how the IpcServer stuff works, I see you are creating and server object but there is only a cleanup() being called on it.

**Comment by parkouss** [comment]
The section of the code in [1] is responsible for checking if an ipc server is running.
If there is none, then there is one created just after the global application in [2]. And creating the IPCServer instance does start to listen for clients to connect (at least should!) as you can see in [3].

[1] https://github.com/parkouss/webmacs/blob/master/webmacs/main.py#L127-L135
[2] https://github.com/parkouss/webmacs/blob/master/webmacs/main.py#L138
[3] https://github.com/parkouss/webmacs/blob/master/webmacs/ipc.py#L89

**Comment by jagguli** [comment]
Ok makes more sense to me, I think the socket is not being created, I should be able to see a socket file created some where right

**Comment by parkouss** [comment]
Exactly, I can see a file /tmp/webmacs.ipc on the computer I'm running currently (fedora).

**Comment by jagguli** [comment]
This seems to be working for me now, weird .
