### ISSUE TITLE
Confused by relative imports / custom folder management

### ISSUE THREAD

**Issue by Mestelan** [parkouss/webmacs#81]
Hello,

Thanks for webmacs, it looks very promising. I am just starting to use it, and have written simple customizations in  `__init__.py`.

Now I would like to organize the customizations in my personal folder. For example, let us start with a simple webjumps.py file:
```
├── init
│   ├── __init__.py
│   ├── __pycache__
│   │   └── __init__.cpython-35.pyc
│   └── webjumps.py

```
Although the documentation suggests:
`__init__.py`

      `import .webjumps`

This does not work here; I get this error:
```
  File "~/.webmacs/init/__init__.py", line 22
    import .webjumps
           ^
SyntaxError: invalid syntax
```

I tried various other syntaxes, to no avail:
```

# from .webjumps import *
# => SystemError: Parent module 'init' not loaded, cannot perform relative import

# from ... import webjumps
# => SystemError: Parent module 'init' not loaded, cannot perform relative import

# from .init import webjumps
# => SystemError: Parent module 'init' not loaded, cannot perform relative import

# import .webjumps
# => SyntaxError: invalid syntax

# import init.webjumps
# => ImportError: No module named 'init'

# import webmacs.init.webjumps
# => ImportError: No module named 'init'
```

(Probably the last 2 make no sense in Python anyway?)

Can you please advise how to achieve this? How do webmacs users organize their folders?

**Comment by parkouss** [comment]
Hm, this might be related to #52, though I just tested and indeed even with the syntax :

`from . import webjumps`

It is broken. Looking into it right now.

**Comment by parkouss** [comment]
Thanks a lot @Mestelan for reporting it! So I fixed the issue, and updated the documentation. The recommended way is now using relative import like this:

`from . import webjumps`
