### ISSUE TITLE
Completion gets truncated when using webjump alias

### ISSUE THREAD

**Issue by Mestelan** [parkouss/webmacs#92]
Hello,
Thanks for merging #91.
Unfortunately, after using it for some time, I have come to realize there is an issue with it.

I have defined
`define_webjump_alias("g", "google")`

Now the 'g' alias does trigger a Google search, but its completion is erroneous. Ex if I type
`google linthesia`
the search term gets completed OK.
But, when typing
`g linthesia`
the search term gets completed to 'esia'.

I have looked into the `minibuffer` package, and it is not yet obvious to me where the problem comes from?

If fixing this behaviour would require drastic changes, I have no objections against your reverting the commit. The alias was meant as a 'nice-to-have', but it is not so nice if it does not integrate into the whole system.

**Comment by parkouss** [comment]
I believe this is fixed by https://github.com/parkouss/webmacs/pull/93. Thanks :)
